name:                xstitch
version:             0.1.0.0
github:              "jbweston/xstitch"
license:             AGPL
author:              "Joseph Weston"
maintainer:          "joseph@weston.cloud"
copyright:           "Copyright (c) 2019 Joseph Weston"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jbweston/xstitch#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  xstitch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xstitch

tests:
  xstitch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xstitch
